// Copyright Team17. All Rights Reserved.
// Auto-generated by Backstage scaffolder

using UnrealBuildTool;

public class ${{ values.projectName }} : ModuleRules
{
    public ${{ values.projectName }}(ReadOnlyTargetRules Target) : base(Target)
    {
        PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;

        PublicDependencyModuleNames.AddRange(new string[]
        {
            "Core",
            "CoreUObject",
            "Engine",
            "InputCore",
            "EnhancedInput",
            {%- if values.engineVersion.startswith('5') %}
            "GameplayAbilities",
            "GameplayTags",
            "GameplayTasks",
            {%- endif %}
        });

        PrivateDependencyModuleNames.AddRange(new string[]
        {
            "Slate",
            "SlateCore",
            "UMG",
        });

        {%- if values.isBackCatalogue %}
        // Legacy compatibility flags for back-catalogue port
        bEnableExceptions = true;
        bUseUnity = false; // Disable unity builds for debugging legacy code
        {%- endif %}

        // Platform-specific configuration
        {%- if 'Android' in values.targetPlatforms %}
        if (Target.Platform == UnrealTargetPlatform.Android)
        {
            PrivateDependencyModuleNames.Add("AndroidPermission");
        }
        {%- endif %}

        {%- if 'iOS' in values.targetPlatforms %}
        if (Target.Platform == UnrealTargetPlatform.IOS)
        {
            PublicFrameworks.Add("GameKit");
            PublicFrameworks.Add("StoreKit");
        }
        {%- endif %}

        {%- if values.enableConsoleSupport %}
        // Console platform support
        if (Target.Platform == UnrealTargetPlatform.PS5 ||
            Target.Platform == UnrealTargetPlatform.XboxSeriesX ||
            Target.Platform == UnrealTargetPlatform.Switch)
        {
            PrivateDependencyModuleNames.Add("OnlineSubsystem");
            PrivateDependencyModuleNames.Add("OnlineSubsystemUtils");
        }
        {%- endif %}
    }
}
