// TeamCity Kotlin DSL Configuration
// Auto-generated by Backstage scaffolder for: ${{ values.projectName }}
// Engine: Unreal Engine ${{ values.engineVersion }}
// Platforms: ${{ values.targetPlatforms | join(', ') }}

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.triggers.schedule

version = "2024.12"

project {
    description = "${{ values.description | default(values.projectName + ' - Unreal Engine Game') }}"

    params {
        // Engine configuration
        param("env.UE_ROOT", "C:\\UnrealEngine\\${{ values.engineVersion }}")
        param("env.PROJECT_NAME", "${{ values.projectName }}")
        param("env.PERFORCE_STREAM", "//Game/${{ values.perforceDepot }}/Main")

        // Build configuration
        param("env.BUILD_CONFIG", "${{ values.buildConfiguration }}")
        param("env.ARTIFACT_RETENTION_DAYS", "${{ values.artifactRetentionDays }}")

        {%- if values.enableDistributedBuild %}
        // Distributed build settings
        param("env.FASTBUILD_BROKERAGE_PATH", "\\\\buildshare\\fb-broker")
        param("env.INCREDIBUILD_ENABLED", "true")
        {%- endif %}
    }

    // VCS Root
    vcsRoot(PerforceRoot)

    // Build Types
    val compile = buildType(CompileEditor)
    {%- for platform in values.targetPlatforms %}
    val cook{{ platform }} = buildType(Cook{{ platform }})
    {%- endfor %}
    val functionalTests = buildType(FunctionalTests)
    val performanceTests = buildType(PerformanceTests)
    val qualityGate = buildType(QualityGate)
    val packageAll = buildType(PackageAll)
    val publishToUGS = buildType(PublishToUGS)

    // Build chain
    sequential {
        buildType(compile)
        parallel {
            {%- for platform in values.targetPlatforms %}
            buildType(cook{{ platform }})
            {%- endfor %}
        }
        parallel {
            buildType(functionalTests)
            buildType(performanceTests)
        }
        buildType(qualityGate)
        buildType(packageAll)
        buildType(publishToUGS)
    }
}

object PerforceRoot : VcsRoot({
    name = "${{ values.projectName }} Perforce"
    type = "perforce"
    param("port", "ssl:perforce.team17.com:1666")
    param("stream", "//Game/${{ values.perforceDepot }}/Main")
    param("user", "teamcity")
    password = "credentialsJSON:perforce-password"
})

object CompileEditor : BuildType({
    name = "Compile Editor"
    description = "Compile editor binaries for all platforms"

    vcs {
        root(PerforceRoot)
        // Partial sync - exclude Content for compile
        checkoutRules = """
            +://Game/${{ values.perforceDepot }}/Main/Source/...
            +://Game/${{ values.perforceDepot }}/Main/Config/...
            +://Game/${{ values.perforceDepot }}/Main/Build/...
            +://Game/${{ values.perforceDepot }}/Main/*.uproject
            -://Game/${{ values.perforceDepot }}/Main/Content/...
        """.trimIndent()
    }

    triggers {
        vcs {
            branchFilter = "+:*"
        }
    }

    steps {
        script {
            name = "Post Badge: Compile Starting"
            scriptContent = """
                curl -X POST http://ugs-metadata.team17.com:5000/api/badges ^
                    -H "Content-Type: application/json" ^
                    -d "{\"project\": \"//Game/${{ values.perforceDepot }}/Main\", \"changelist\": %build.vcs.number%, \"badge\": \"Compile\", \"status\": \"Starting\"}"
            """.trimIndent()
        }

        script {
            name = "Compile Editor (Distributed)"
            scriptContent = """
                {%- if values.enableDistributedBuild %}
                set FASTBUILD_BROKERAGE_PATH=%env.FASTBUILD_BROKERAGE_PATH%
                {%- endif %}

                %env.UE_ROOT%\Build\BatchFiles\RunUAT.bat BuildCookRun ^
                    -project="%teamcity.build.checkoutDir%\${{ values.projectName }}.uproject" ^
                    -platform=Win64 ^
                    -nocompileeditor -installed ^
                    -build ^
                    {%- if values.isBackCatalogue %}
                    -LEGACY_UE4_SUPPORT ^
                    {%- endif %}
                    -skipcook
            """.trimIndent()
        }

        script {
            name = "Post Badge: Compile Success"
            scriptContent = """
                curl -X POST http://ugs-metadata.team17.com:5000/api/badges ^
                    -H "Content-Type: application/json" ^
                    -d "{\"project\": \"//Game/${{ values.perforceDepot }}/Main\", \"changelist\": %build.vcs.number%, \"badge\": \"Compile\", \"status\": \"Success\"}"
            """.trimIndent()
        }
    }

    artifactRules = """
        Binaries/** => Editor-Binaries.zip
        build.log
    """.trimIndent()

    requirements {
        equals("system.agent.type", "compile")
        {%- if values.enableDistributedBuild %}
        exists("system.incredibuild.installed")
        {%- endif %}
    }
})

{%- for platform in values.targetPlatforms %}

object Cook{{ platform }} : BuildType({
    name = "Cook {{ platform }}"
    description = "Cook content for {{ platform }}"

    vcs {
        root(PerforceRoot)
        // Full sync including Content
        checkoutRules = "+://Game/${{ values.perforceDepot }}/Main/..."
    }

    dependencies {
        snapshot(CompileEditor) {
            onDependencyFailure = FailureAction.FAIL_TO_START
        }
    }

    steps {
        script {
            name = "Cook with Shared DDC"
            scriptContent = """
                %env.UE_ROOT%\Build\BatchFiles\RunUAT.bat BuildCookRun ^
                    -project="${{ values.projectName }}.uproject" ^
                    -platform={{ platform }} ^
                    -clientconfig=%env.BUILD_CONFIG% ^
                    -nocompileeditor -installed ^
                    -cook ^
                    -iterativecooking ^
                    -DDC=Shared
            """.trimIndent()
        }
    }

    artifactRules = "Saved/Cooked/{{ platform }}/** => Cooked-{{ platform }}.zip"

    requirements {
        equals("system.agent.type", "cook")
        moreThan("system.disk.free.gb", "200")
        {%- if platform == 'iOS' %}
        contains("teamcity.agent.jvm.os.name", "Mac")
        {%- endif %}
        {%- if platform in ['PS5', 'Xbox', 'Switch'] %}
        exists("system.{{ platform | lower }}.sdk.installed")
        {%- endif %}
    }
})
{%- endfor %}

object FunctionalTests : BuildType({
    name = "Functional Tests (Gauntlet)"
    description = "Run automated functional tests"

    dependencies {
        snapshot(CookWin64) {
            onDependencyFailure = FailureAction.FAIL_TO_START
        }
    }

    steps {
        script {
            name = "Run Gauntlet Tests"
            scriptContent = """
                %env.UE_ROOT%\Build\BatchFiles\RunUAT.bat RunUnreal ^
                    -project="${{ values.projectName }}.uproject" ^
                    -platform=Win64 ^
                    -test=${{ values.projectName }}.Tests ^
                    -testfilter=Smoke+Functional ^
                    -nullrhi ^
                    -unattended ^
                    -ReportOutputPath="TestResults"
            """.trimIndent()
        }
    }

    features {
        feature {
            type = "xml-report-plugin"
            param("xmlReportParsing.reportType", "junit")
            param("xmlReportParsing.reportDirs", "TestResults/**/*.xml")
        }
    }
})

object PerformanceTests : BuildType({
    name = "Performance Tests (NFT)"
    description = "Run performance benchmarks"

    dependencies {
        snapshot(CookWin64) {
            onDependencyFailure = FailureAction.FAIL_TO_START
        }
    }

    steps {
        script {
            name = "Run Performance Benchmark"
            scriptContent = """
                %env.UE_ROOT%\Build\BatchFiles\RunUAT.bat RunUnreal ^
                    -project="${{ values.projectName }}.uproject" ^
                    -test=${{ values.projectName }}.PerfTests ^
                    -benchmarkmode ^
                    -seconds=60 ^
                    -ReportOutputPath="PerfResults"
            """.trimIndent()
        }
    }

    requirements {
        equals("system.agent.type", "perf-benchmark")
    }
})

object QualityGate : BuildType({
    name = "Quality Gate"
    description = "All tests must pass before packaging"
    type = BuildTypeSettings.Type.COMPOSITE

    dependencies {
        snapshot(CompileEditor) { onDependencyFailure = FailureAction.FAIL_TO_START }
        snapshot(FunctionalTests) { onDependencyFailure = FailureAction.FAIL_TO_START }
        snapshot(PerformanceTests) { onDependencyFailure = FailureAction.FAIL_TO_START }
    }
})

object PackageAll : BuildType({
    name = "Package All Platforms"
    description = "Create distributable packages"

    dependencies {
        snapshot(QualityGate) { onDependencyFailure = FailureAction.FAIL_TO_START }
        {%- for platform in values.targetPlatforms %}
        artifacts(Cook{{ platform }}) {
            artifactRules = "Cooked-{{ platform }}.zip => Saved/Cooked/"
        }
        {%- endfor %}
    }

    steps {
        {%- for platform in values.targetPlatforms %}
        script {
            name = "Package {{ platform }}"
            scriptContent = """
                %env.UE_ROOT%\Build\BatchFiles\RunUAT.bat BuildCookRun ^
                    -project="${{ values.projectName }}.uproject" ^
                    -platform={{ platform }} ^
                    -clientconfig=%env.BUILD_CONFIG% ^
                    -skipcook ^
                    -stage -package -archive ^
                    -archivedirectory="Packages/{{ platform }}"
            """.trimIndent()
        }
        {%- endfor %}
    }

    artifactRules = "Packages/** => Packages.zip"
})

object PublishToUGS : BuildType({
    name = "Publish to UGS"
    description = "Publish binaries and post Ready badge"

    dependencies {
        snapshot(PackageAll) {}
        artifacts(CompileEditor) {
            artifactRules = "Editor-Binaries.zip => UGS/Editor/"
        }
    }

    steps {
        script {
            name = "Submit to Perforce UGS Depot"
            scriptContent = """
                set CL=%build.vcs.number%

                p4 reconcile //Game/${{ values.perforceDepot }}/UGS/%CL%/...
                p4 submit -d "[UGS] Build %CL% - Editor and Cooked content"
            """.trimIndent()
        }

        script {
            name = "Post Ready Badge"
            scriptContent = """
                curl -X POST http://ugs-metadata.team17.com:5000/api/badges ^
                    -H "Content-Type: application/json" ^
                    -d "{\"project\": \"//Game/${{ values.perforceDepot }}/Main\", \"changelist\": %build.vcs.number%, \"badge\": \"Ready\", \"status\": \"Success\"}"
            """.trimIndent()
        }
    }
})
